import crypto from 'node:crypto'

/**
 * Generates an official, standards-compliant Nordcraft Project AST
 * conforming to @nordcraft/core schema specifications.
 */
export function createProject({
  id = crypto.randomUUID(),
  name = 'Untitled Nordcraft App',
  description = 'Autonomous Application generated by Producer Cue & Nordcraft Engine',
  shortId = 'producer_cue_app',
  emoji = '🎬',
} = {}) {
  return {
    id,
    name,
    project: {
      id: crypto.randomUUID(),
      short_id: shortId,
      emoji,
      name,
      description,
      custom_domains: false,
      type: 'app',
      published_at: null,
      thumbnail: null,
      accounts: {
        name: 'projectcues-org',
        account_plans: { plans: { custom_domains: false } },
      },
    },
    commit: crypto.randomBytes(20).toString('hex'),
    files: {
      components: {},
      actions: {},
      formulas: {},
      config: {},
      packages: {},
      themes: {
        Default: {
          color: [
            {
              name: 'brand',
              tokens: [
                { name: 'brand-50', type: 'value', value: '#F0FDF4' },
                { name: 'brand-500', type: 'value', value: '#22C55E' },
                { name: 'brand-600', type: 'value', value: '#16A34A' },
                { name: 'brand-900', type: 'value', value: '#14532D' },
              ],
            },
            {
              name: 'slate',
              tokens: [
                { name: 'slate-50', type: 'value', value: '#F8FAFC' },
                { name: 'slate-100', type: 'value', value: '#F1F5F9' },
                { name: 'slate-200', type: 'value', value: '#E2E8F0' },
                { name: 'slate-300', type: 'value', value: '#CBD5E1' },
                { name: 'slate-400', type: 'value', value: '#94A3B8' },
                { name: 'slate-500', type: 'value', value: '#64748B' },
                { name: 'slate-600', type: 'value', value: '#475569' },
                { name: 'slate-700', type: 'value', value: '#334155' },
                { name: 'slate-800', type: 'value', value: '#1E293B' },
                { name: 'slate-900', type: 'value', value: '#0F172A' },
              ],
            },
          ],
        },
      },
    },
  }
}

/**
 * Creates an official Nordcraft Component structure
 */
export function createComponent({
  name = 'HomePage',
  isPage = true,
  path = [],
  title = 'Nordcraft App',
  description = 'Built with Nordcraft & Producer Cue',
} = {}) {
  const component = {
    name,
    apis: {},
    nodes: {
      root: {
        tag: 'div',
        type: 'element',
        attrs: {},
        style: {
          'min-height': '100%',
          'display': 'flex',
          'flex-direction': 'column',
          'background-color': 'var(--slate-50)',
          'font-family': 'sans-serif',
        },
        events: {},
        classes: {},
        children: [],
        styleVariables: {},
      },
    },
    events: [],
    onLoad: { actions: [], trigger: 'load' },
    functions: {},
    variables: {},
    attributes: {},
  }

  if (isPage) {
    component.route = {
      info: {
        title: { formula: { type: 'value', value: title } },
        description: { formula: { type: 'value', value: description } },
      },
      path,
      query: {},
    }
  }

  return component
}

/**
 * Inserts a Node (Element, Text, or Component instance) into a Component's AST
 */
export function addNode(
  component,
  {
    id = crypto.randomUUID().slice(0, 12),
    parentId = 'root',
    tag = 'div',
    type = 'element',
    style = {},
    attrs = {},
    classes = {},
    events = {},
    text = null,
    children = [],
  } = {}
) {
  if (type === 'text') {
    component.nodes[id] = {
      type: 'text',
      value: { type: 'value', value: text ?? '' },
    }
  } else {
    component.nodes[id] = {
      tag,
      type: 'element',
      attrs,
      style,
      events,
      classes,
      children,
      styleVariables: {},
    }
  }

  // Attach to parent if parent exists
  if (component.nodes[parentId] && Array.isArray(component.nodes[parentId].children)) {
    if (!component.nodes[parentId].children.includes(id)) {
      component.nodes[parentId].children.push(id)
    }
  }

  return id
}

/**
 * Adds a reactive variable (signal) to a Component
 */
export function addVariable(component, name, initialValue) {
  component.variables[name] = {
    initialValue: { type: 'value', value: initialValue },
  }
}

/**
 * Adds an external REST API binding to a Component (e.g. NoCodeBackend)
 */
export function addApi(
  component,
  name,
  {
    url,
    method = 'GET',
    headers = {},
    autoFetch = true,
  } = {}
) {
  component.apis[name] = {
    name,
    type: 'http',
    url: { type: 'value', value: url },
    method,
    headers: Object.entries(headers).map(([key, val]) => ({
      name: key,
      value: { type: 'value', value: val },
    })),
    autoFetch,
  }
}
