export function exportToWebComponent(component, tagName) {
  const compName = component.name || 'CustomWidget'
  const customTag =
    tagName ||
    `nc-${compName
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .toLowerCase()}`

  return `/**
 * Standalone Custom Web Element: <${customTag}>
 * Generated by Producer Cue (Project Cues, Inc.)
 */

export class ${compName}Element extends HTMLElement {
  static get observedAttributes() {
    return ${JSON.stringify(Object.keys(component.attributes || {}))};
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.state = ${JSON.stringify(
      Object.fromEntries(
        Object.entries(component.variables || {}).map(([k, v]) => [
          k,
          v.initialValue?.value,
        ]),
      ),
    )};
  }

  connectedCallback() {
    this.render();
  }

  attributeChangedCallback(name, oldValue, newValue) {
    if (oldValue !== newValue) {
      this.render();
    }
  }

  setState(updates) {
    this.state = { ...this.state, ...updates };
    this.render();
  }

  render() {
    if (!this.shadowRoot) return;

    this.shadowRoot.innerHTML = \`
      <style>
        :host {
          display: block;
          font-family: system-ui, -apple-system, sans-serif;
        }
      </style>
      <div>
        <slot></slot>
      </div>
    \`;
  }
}

if (!customElements.get('${customTag}')) {
  customElements.define('${customTag}', ${compName}Element);
}
`
}
